/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import {TiWeatherPartlySunny} from 'react-icons/ti'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Live Weather - Open Weather Api</title>
        <meta name="description" content="Live  Weather Generated by OpenWeather API " />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='mx-2 lg:mx-20 relative'>
        <div className='flex justify-center mt-20'>
          <div className='w-full flex flex-col max-w-[500px] space-y-5 justify-center items-center'>
              <TiWeatherPartlySunny className='text-yellow-300' size={300}/>
              <h1 className='text-white font-bold text-2xl lg:text-4xl'>Check Weather in Your City</h1>
          </div>
        </div>
      </div>
    </div>
  )
}
